dist: bionic
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
matrix:
  include:
    - python: "2.5"
      dist: precise
    - python: "2.6"
      dist: trusty
    - python: "3.3"
      dist: trusty
install:
  - pip install -r requirements.txt
script:
  - pytest .
cache: pip
